/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layer_Presentation;

import Layer_Business.LB_Association;
import Layer_Business.LB_Church;
import Layer_Business.LB_District;
import Layer_Business.LB_IDGenerator;
import Layer_Business.LB_KeyEvent;
import Layer_Business.LB_Reservation;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author KGR
 */
public class JDPastor extends java.awt.Dialog {

    /**
     * Creates new form JDLevel
     */
    LB_Association LBA = new LB_Association();
    LB_District LB = new LB_District();
    LB_KeyEvent LBKE = new LB_KeyEvent();
    public Boolean Actualizar = false;
    String Response;
    public String ID;
    
    public JDPastor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        ListDistrict();
    }
    
    public void ListDistrict()
    {
        LBA.ListAssociation(this.jComboBox_ID_Association);
    }
    
     public void GetDataAssociation()
    {
        LB_Association r =  (LB_Association) this.jComboBox_ID_Association.getSelectedItem();
        String id = r.getID_Association();
        this.jLabel_IDDistrict.setText(id);
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_ID_District = new javax.swing.JTextField();
        jSpinner_Length = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jTextField_String = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jComboBox_ID_Association = new javax.swing.JComboBox<>();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel_IDDistrict = new javax.swing.JLabel();
        jButton_Save = new javax.swing.JButton();
        jPanel_Sidebar = new javax.swing.JPanel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jTabbedPane3.setBackground(new java.awt.Color(240, 240, 240));
        jTabbedPane3.setForeground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(119, 123, 125));
        jLabel6.setText("ID");

        jSeparator5.setBackground(new java.awt.Color(26, 97, 186));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(119, 123, 125));
        jLabel7.setText("Name");

        jSeparator6.setBackground(new java.awt.Color(26, 97, 186));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(119, 123, 125));
        jLabel14.setText("Length");

        jSeparator13.setBackground(new java.awt.Color(26, 97, 186));

        jTextField_Name.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_Name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_Name.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_Name.setBorder(null);
        jTextField_Name.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NameKeyTyped(evt);
            }
        });

        jTextField_ID_District.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_ID_District.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_ID_District.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_ID_District.setBorder(null);
        jTextField_ID_District.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_ID_District.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ID_DistrictKeyTyped(evt);
            }
        });

        jSpinner_Length.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jSpinner_Length.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_LengthStateChanged(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(119, 123, 125));
        jLabel15.setText("String");

        jTextField_String.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_String.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_String.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_String.setText("Res");
        jTextField_String.setBorder(null);
        jTextField_String.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_String.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_StringKeyTyped(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(119, 123, 125));
        jLabel24.setText("Association");

        jComboBox_ID_Association.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_ID_Association.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_ID_Association.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_ID_Association.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ID_AssociationItemStateChanged(evt);
            }
        });

        jSeparator23.setBackground(new java.awt.Color(26, 97, 186));

        jLabel_IDDistrict.setForeground(new java.awt.Color(105, 105, 105));
        jLabel_IDDistrict.setText("ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_IDDistrict)
                    .addComponent(jLabel24)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator13)
                            .addComponent(jLabel6)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_ID_District, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSpinner_Length, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_String, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator6)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                    .addComponent(jSeparator23)
                    .addComponent(jComboBox_ID_Association, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_ID_District, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_Length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_String, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_ID_Association, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_IDDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jTabbedPane3.addTab("Pág 1", jPanel3);

        jButton_Save.setBackground(new java.awt.Color(214, 61, 92));
        jButton_Save.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Save.setText("Save");
        jButton_Save.setToolTipText("");
        jButton_Save.setBorder(null);
        jButton_Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Save.setFocusable(false);
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jTabbedPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel_Sidebar.setBackground(new java.awt.Color(81, 172, 186));
        jPanel_Sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseDragged(evt);
            }
        });
        jPanel_Sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseReleased(evt);
            }
        });

        jLabel_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/left_15px.png"))); // NOI18N
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 63, 65));
        jLabel1.setText("PASTOR");

        javax.swing.GroupLayout jPanel_SidebarLayout = new javax.swing.GroupLayout(jPanel_Sidebar);
        jPanel_Sidebar.setLayout(jPanel_SidebarLayout);
        jPanel_SidebarLayout.setHorizontalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close)
                .addGap(263, 263, 263)
                .addComponent(jLabel1)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        jPanel_SidebarLayout.setVerticalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        add(jPanel_Sidebar, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jTextField_NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NameKeyTyped
        // TODO add your handling code here:
        LBKE.CharactersMayusAndCharactersMin(evt);
    }//GEN-LAST:event_jTextField_NameKeyTyped

    private void jTextField_ID_DistrictKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ID_DistrictKeyTyped
        // TODO add your handling code here:
        LBKE.CharactersMayusAndCharactersMin(evt);
    }//GEN-LAST:event_jTextField_ID_DistrictKeyTyped

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:

        if (!"".equals(jTextField_ID_District.getText()))
        {
                if (!"".equals(jTextField_Name.getText()))
                {
                        String ID_District = jTextField_ID_District.getText();
                        String Name = jTextField_Name.getText();
                        //String ID_Association = jComboBox_ID_Association.getSelectedItem().toString();

                        LB_Association r =  (LB_Association) this.jComboBox_ID_Association.getSelectedItem();
                        String id = r.getID_Association();
        
                        if (Actualizar == true)
                        {
                            //UPDATE

                            LB = new LB_District(ID, Name, id);

                            Response = LB.Update();
                            if (LB.eye > 0)
                            {
                                JOptionPane.showMessageDialog(null, "Reservation " + LB.getID_District()+ "\n" + Response, "MF Control - District", JOptionPane.INFORMATION_MESSAGE);
                                //listar
                                //this.dispose();
                            }
                            Actualizar = false;
                        }
                        else
                        {
                            //SAVE

                            LB = new LB_District(ID_District, Name, id);

                            //Insert CIF
                            String rptaRegistro = LB.Insert();

                            if (rptaRegistro != null)
                            {
                                JOptionPane.showMessageDialog(null, "Reservation " + ID_District + "\n" + rptaRegistro, "MF Control - District", JOptionPane.INFORMATION_MESSAGE);
                                //listar
                                //this.dispose();
                            }
                        }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "The Name Is Required !", "MF Control - District", JOptionPane.WARNING_MESSAGE);
                }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "The ID Is Required !", "MF Control - District", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        // TODO add your handling code here:
        JFManageDistrict viewR = new JFManageDistrict();

        //Mostrar vista Principal
        viewR.setLocationRelativeTo(null);
        //Guardar datos en variables
        this.dispose();
        viewR.setVisible(true);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    int xy, xx;
    private void jPanel_SidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel_SidebarMouseDragged

    private void jPanel_SidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel_SidebarMousePressed

    private void jPanel_SidebarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_jPanel_SidebarMouseReleased

    private void jSpinner_LengthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_LengthStateChanged
        // TODO add your handling code here:
        LB_IDGenerator IG = new LB_IDGenerator();
        String val = jTextField_String.getText();
        int Length = Integer.parseInt(this.jSpinner_Length.getValue().toString());
        
        String ID = IG.getIDs(val, Length);
        
        jTextField_ID_District.setText("Dist"+ID);
        
    }//GEN-LAST:event_jSpinner_LengthStateChanged

    private void jTextField_StringKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_StringKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_StringKeyTyped

    private void jComboBox_ID_AssociationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ID_AssociationItemStateChanged
        // TODO add your handling code here:
        GetDataAssociation();
    }//GEN-LAST:event_jComboBox_ID_AssociationItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDPastor dialog = new JDPastor(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Save;
    private javax.swing.JComboBox<String> jComboBox_ID_Association;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_IDDistrict;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Sidebar;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JSpinner jSpinner_Length;
    private javax.swing.JTabbedPane jTabbedPane3;
    public javax.swing.JTextField jTextField_ID_District;
    public javax.swing.JTextField jTextField_Name;
    public javax.swing.JTextField jTextField_String;
    // End of variables declaration//GEN-END:variables
}
