/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layer_Presentation;

import Layer_Business.LB_IDGenerator;
import Layer_Business.LB_KeyEvent;
import Layer_Business.LB_Reservation;
import java.text.SimpleDateFormat;
import java.util.TimeZone;
import javax.swing.JOptionPane;

/**
 *
 * @author KGR
 */
public class JDReservation extends java.awt.Dialog {

    /**
     * Creates new form JDLevel
     */
    LB_Reservation LB = new LB_Reservation();
    LB_KeyEvent LBKE = new LB_KeyEvent();
    public Boolean Actualizar = false;
    String Response;
    public String ID;
    
    public JDReservation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }
    
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jComboBox_PaymentStatus = new javax.swing.JComboBox<>();
        jTextField_Payment = new javax.swing.JTextField();
        jTextField_IDReservation = new javax.swing.JTextField();
        jPanel_OpeningDate = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jDateChooser_DateAndTime = new com.toedter.calendar.JDateChooser();
        jSeparator23 = new javax.swing.JSeparator();
        jButton_Save = new javax.swing.JButton();
        jLabel_IDCareer = new javax.swing.JLabel();
        jSpinner_Length = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jTextField_IDNames = new javax.swing.JTextField();
        jPanel_Sidebar = new javax.swing.JPanel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jTabbedPane3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(119, 123, 125));
        jLabel6.setText("ID");

        jSeparator5.setBackground(new java.awt.Color(26, 97, 186));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(119, 123, 125));
        jLabel7.setText("Payment");

        jSeparator6.setBackground(new java.awt.Color(26, 97, 186));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(119, 123, 125));
        jLabel14.setText("Length");

        jSeparator13.setBackground(new java.awt.Color(26, 97, 186));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(119, 123, 125));
        jLabel20.setText("PaymentStatus");

        jSeparator19.setBackground(new java.awt.Color(26, 97, 186));

        jComboBox_PaymentStatus.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox_PaymentStatus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_PaymentStatus.setForeground(new java.awt.Color(105, 105, 105));
        jComboBox_PaymentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Credit", "Paid" }));

        jTextField_Payment.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_Payment.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_Payment.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_Payment.setBorder(null);
        jTextField_Payment.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_Payment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PaymentKeyTyped(evt);
            }
        });

        jTextField_IDReservation.setEditable(false);
        jTextField_IDReservation.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_IDReservation.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_IDReservation.setBorder(null);
        jTextField_IDReservation.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_IDReservation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IDReservationKeyTyped(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(119, 123, 125));
        jLabel24.setText("DateAndTime");

        jDateChooser_DateAndTime.setForeground(new java.awt.Color(105, 105, 105));
        jDateChooser_DateAndTime.setDateFormatString("d MMM y - kk:mm:ss ");
        jDateChooser_DateAndTime.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jSeparator23.setBackground(new java.awt.Color(26, 97, 186));

        jButton_Save.setBackground(new java.awt.Color(214, 61, 92));
        jButton_Save.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Save.setText("Save");
        jButton_Save.setToolTipText("");
        jButton_Save.setBorder(null);
        jButton_Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Save.setFocusable(false);
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_OpeningDateLayout = new javax.swing.GroupLayout(jPanel_OpeningDate);
        jPanel_OpeningDate.setLayout(jPanel_OpeningDateLayout);
        jPanel_OpeningDateLayout.setHorizontalGroup(
            jPanel_OpeningDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_OpeningDateLayout.createSequentialGroup()
                .addGroup(jPanel_OpeningDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_OpeningDateLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel_OpeningDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator23)
                            .addComponent(jLabel24)
                            .addComponent(jDateChooser_DateAndTime, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                    .addGroup(jPanel_OpeningDateLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_OpeningDateLayout.setVerticalGroup(
            jPanel_OpeningDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_OpeningDateLayout.createSequentialGroup()
                .addComponent(jLabel24)
                .addGap(24, 24, 24)
                .addComponent(jDateChooser_DateAndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel_IDCareer.setForeground(new java.awt.Color(105, 105, 105));
        jLabel_IDCareer.setText("ID");

        jSpinner_Length.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jSpinner_Length.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_LengthStateChanged(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(119, 123, 125));
        jLabel15.setText("String");

        jTextField_IDNames.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_IDNames.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField_IDNames.setForeground(new java.awt.Color(105, 105, 105));
        jTextField_IDNames.setBorder(null);
        jTextField_IDNames.setMaximumSize(new java.awt.Dimension(0, 19));
        jTextField_IDNames.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IDNamesKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_IDCareer)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator13)
                            .addComponent(jSeparator19)
                            .addComponent(jComboBox_PaymentStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSpinner_Length, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_IDNames, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                            .addComponent(jTextField_IDReservation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator6)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField_Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74))
                            .addComponent(jPanel_OpeningDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_IDReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addGap(19, 19, 19)
                        .addComponent(jComboBox_PaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_Length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_IDNames, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel_OpeningDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_IDCareer)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Pág 1", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jTabbedPane3)
                .addGap(72, 72, 72))
        );

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel_Sidebar.setBackground(new java.awt.Color(81, 172, 186));
        jPanel_Sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseDragged(evt);
            }
        });
        jPanel_Sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel_SidebarMouseReleased(evt);
            }
        });

        jLabel_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/left_15px.png"))); // NOI18N
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 63, 65));
        jLabel1.setText("RESERVATION");

        javax.swing.GroupLayout jPanel_SidebarLayout = new javax.swing.GroupLayout(jPanel_Sidebar);
        jPanel_Sidebar.setLayout(jPanel_SidebarLayout);
        jPanel_SidebarLayout.setHorizontalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close)
                .addGap(263, 263, 263)
                .addComponent(jLabel1)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanel_SidebarLayout.setVerticalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        add(jPanel_Sidebar, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jTextField_PaymentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PaymentKeyTyped
        // TODO add your handling code here:
        LBKE.Numbers(evt);
    }//GEN-LAST:event_jTextField_PaymentKeyTyped

    private void jTextField_IDReservationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDReservationKeyTyped
        // TODO add your handling code here:
        LBKE.CharactersMayusAndCharactersMin(evt);
    }//GEN-LAST:event_jTextField_IDReservationKeyTyped

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:

        if (!"".equals(jTextField_IDReservation.getText()))
        {
                if (!"".equals(jTextField_Payment.getText()))
                {
                    if (jDateChooser_DateAndTime.getCalendar() != null)
                    {
                        String IDReservation = jTextField_IDReservation.getText();
                        
                        String PaymentStatus = jComboBox_PaymentStatus.getSelectedItem().toString();
                        String Payment = jTextField_Payment.getText();
                        TimeZone zone = TimeZone.getTimeZone("America/El_Salvador");
                        
                        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd - kk:mm:ss");
                        dateFormat.setTimeZone(TimeZone.getTimeZone("America/El_Salvador"));
                        String DateAndTime = dateFormat.format(jDateChooser_DateAndTime.getDate());

                        if (Actualizar == true)
                        {
                            //UPDATE

                            LB = new LB_Reservation(ID, PaymentStatus,
                                Float.valueOf(Payment), DateAndTime);

                            Response = LB.Update();
                            if (LB.eye > 0)
                            {
                                JOptionPane.showMessageDialog(null, "Reservation " + LB.getID_reservation()+ "\n" + Response, "MF Control - Reservation", JOptionPane.INFORMATION_MESSAGE);
                                //listar
                                //this.dispose();
                            }
                            Actualizar = false;
                        }
                        else
                        {
                            //SAVE

                            LB = new LB_Reservation(IDReservation, PaymentStatus,
                            Float.valueOf(Payment), DateAndTime);

                            //Insert CIF
                            String rptaRegistro = LB.Insert();

                            if (rptaRegistro != null)
                            {
                                JOptionPane.showMessageDialog(null, "Reservation " + IDReservation + "\n" + rptaRegistro, "MF Control - Reservation", JOptionPane.INFORMATION_MESSAGE);
                                //listar
                                //this.dispose();
                            }
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "The OpeningDate Is Required !", "MF Control - Reservation", JOptionPane.WARNING_MESSAGE);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "The Payment Is Required !", "MF Control - Reservation", JOptionPane.WARNING_MESSAGE);
                }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "The ID Is Required !", "MF Control - Reservation", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        // TODO add your handling code here:
        JFManageReservation viewR = new JFManageReservation();

        //Mostrar vista Principal
        viewR.setLocationRelativeTo(null);
        //Guardar datos en variables
        this.dispose();
        viewR.setVisible(true);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    int xy, xx;
    private void jPanel_SidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel_SidebarMouseDragged

    private void jPanel_SidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel_SidebarMousePressed

    private void jPanel_SidebarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_SidebarMouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_jPanel_SidebarMouseReleased

    private void jSpinner_LengthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_LengthStateChanged
        // TODO add your handling code here:
        LB_IDGenerator IG = new LB_IDGenerator();
        int Length = Integer.parseInt(this.jSpinner_Length.getValue().toString());
        
        String ID = IG.getIDs("",Length);
        
        jTextField_IDReservation.setText("Rese"+ jTextField_IDNames.getText() +ID);
        
    }//GEN-LAST:event_jSpinner_LengthStateChanged

    private void jTextField_IDNamesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDNamesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDNamesKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDReservation dialog = new JDReservation(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Save;
    private javax.swing.JComboBox<String> jComboBox_PaymentStatus;
    public com.toedter.calendar.JDateChooser jDateChooser_DateAndTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_IDCareer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel_OpeningDate;
    private javax.swing.JPanel jPanel_Sidebar;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JSpinner jSpinner_Length;
    private javax.swing.JTabbedPane jTabbedPane3;
    public javax.swing.JTextField jTextField_IDNames;
    public javax.swing.JTextField jTextField_IDReservation;
    public javax.swing.JTextField jTextField_Payment;
    // End of variables declaration//GEN-END:variables
}
